import React from "react";
function Comp2(){
    return(
        <div>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            <h1>This Is Comp 2......</h1>
            
        </div>
    )
}
export default Comp2;